import type { TeamAliasEntry } from "./schemas";

export const teamAliasEntries: TeamAliasEntry[] = [
  { teamId: "arg", aliases: ["Argentina", "ARG"] },
  { teamId: "fra", aliases: ["France", "FRA"] },
  { teamId: "bra", aliases: ["Brazil", "BRA"] },
  { teamId: "eng", aliases: ["England", "ENG"] },
  { teamId: "esp", aliases: ["Spain", "ESP"] },
  { teamId: "ger", aliases: ["Germany", "GER"] },
  { teamId: "por", aliases: ["Portugal", "POR"] },
  { teamId: "ned", aliases: ["Netherlands", "NED", "Holland"] },
  { teamId: "ita", aliases: ["Italy", "ITA"] },
  { teamId: "bel", aliases: ["Belgium", "BEL"] },
  { teamId: "cro", aliases: ["Croatia", "CRO"] },
  { teamId: "uru", aliases: ["Uruguay", "URU"] },
  { teamId: "col", aliases: ["Colombia", "COL"] },
  { teamId: "mex", aliases: ["Mexico", "MEX"] },
  { teamId: "usa", aliases: ["United States", "USA", "United States of America"] },
  { teamId: "sui", aliases: ["Switzerland", "SUI"] },
  { teamId: "den", aliases: ["Denmark", "DEN"] },
  { teamId: "mar", aliases: ["Morocco", "MAR"] },
  { teamId: "jpn", aliases: ["Japan", "JPN"] },
  { teamId: "sen", aliases: ["Senegal", "SEN"] },
  { teamId: "kor", aliases: ["South Korea", "KOR", "Korea Republic"] },
  { teamId: "ecu", aliases: ["Ecuador", "ECU"] },
  { teamId: "pol", aliases: ["Poland", "POL"] },
  { teamId: "srb", aliases: ["Serbia", "SRB"] },
  { teamId: "aus", aliases: ["Australia", "AUS"] },
  { teamId: "can", aliases: ["Canada", "CAN"] },
  { teamId: "nga", aliases: ["Nigeria", "NGA"] },
  { teamId: "gha", aliases: ["Ghana", "GHA"] },
  { teamId: "ksa", aliases: ["Saudi Arabia", "KSA"] },
  { teamId: "qat", aliases: ["Qatar", "QAT"] },
  { teamId: "crc", aliases: ["Costa Rica", "CRC"] },
  { teamId: "nzl", aliases: ["New Zealand", "NZL"] },
];

