import type { TeamAliasEntry } from "./schemas.ts";

export const teamAliasEntries: TeamAliasEntry[] = [
  { teamId: "arg", aliases: ["Argentina", "ARG"] },
  { teamId: "fra", aliases: ["France", "FRA"] },
  { teamId: "bra", aliases: ["Brazil", "BRA"] },
  { teamId: "eng", aliases: ["England", "ENG"] },
  { teamId: "esp", aliases: ["Spain", "ESP"] },
  { teamId: "ger", aliases: ["Germany", "GER"] },
  { teamId: "por", aliases: ["Portugal", "POR"] },
  { teamId: "ned", aliases: ["Netherlands", "NED", "Holland"] },
  { teamId: "aut", aliases: ["Austria", "AUT"] },
  { teamId: "bel", aliases: ["Belgium", "BEL"] },
  { teamId: "cro", aliases: ["Croatia", "CRO"] },
  { teamId: "uru", aliases: ["Uruguay", "URU"] },
  { teamId: "col", aliases: ["Colombia", "COL"] },
  { teamId: "mex", aliases: ["Mexico", "MEX"] },
  { teamId: "usa", aliases: ["United States", "USA", "United States of America"] },
  { teamId: "sui", aliases: ["Switzerland", "SUI"] },
  { teamId: "sco", aliases: ["Scotland", "SCO"] },
  { teamId: "mar", aliases: ["Morocco", "MAR"] },
  { teamId: "jpn", aliases: ["Japan", "JPN"] },
  { teamId: "sen", aliases: ["Senegal", "SEN"] },
  { teamId: "kor", aliases: ["South Korea", "KOR", "Korea Republic"] },
  { teamId: "ecu", aliases: ["Ecuador", "ECU"] },
  { teamId: "swe", aliases: ["Sweden", "SWE"] },
  { teamId: "civ", aliases: ["Ivory Coast", "Côte d'Ivoire", "Cote d'Ivoire", "CIV"] },
  { teamId: "aus", aliases: ["Australia", "AUS"] },
  { teamId: "can", aliases: ["Canada", "CAN"] },
  { teamId: "uzb", aliases: ["Uzbekistan", "UZB"] },
  { teamId: "gha", aliases: ["Ghana", "GHA"] },
  { teamId: "ksa", aliases: ["Saudi Arabia", "KSA"] },
  { teamId: "qat", aliases: ["Qatar", "QAT"] },
  { teamId: "jor", aliases: ["Jordan", "JOR"] },
  { teamId: "nzl", aliases: ["New Zealand", "NZL"] },
];

export const tournamentTeamAliasEntries: TeamAliasEntry[] = [
  { teamId: "aus", aliases: ["Australia", "AUS"] },
  { teamId: "irn", aliases: ["Iran", "IRN", "Iran (Islamic Republic of)"] },
  { teamId: "irq", aliases: ["Iraq", "IRQ"] },
  { teamId: "jpn", aliases: ["Japan", "JPN"] },
  { teamId: "jor", aliases: ["Jordan", "JOR"] },
  { teamId: "qat", aliases: ["Qatar", "QAT"] },
  { teamId: "ksa", aliases: ["Saudi Arabia", "KSA"] },
  { teamId: "kor", aliases: ["South Korea", "KOR", "Korea Republic"] },
  { teamId: "uzb", aliases: ["Uzbekistan", "UZB"] },
  { teamId: "alg", aliases: ["Algeria", "ALG"] },
  { teamId: "cpv", aliases: ["Cape Verde", "CPV", "Cabo Verde"] },
  { teamId: "cod", aliases: ["DR Congo", "Congo DR", "Democratic Republic of the Congo", "COD"] },
  { teamId: "egy", aliases: ["Egypt", "EGY"] },
  { teamId: "gha", aliases: ["Ghana", "GHA"] },
  { teamId: "civ", aliases: ["Ivory Coast", "Côte d'Ivoire", "Cote d'Ivoire", "CIV"] },
  { teamId: "mar", aliases: ["Morocco", "MAR"] },
  { teamId: "sen", aliases: ["Senegal", "SEN"] },
  { teamId: "rsa", aliases: ["South Africa", "RSA"] },
  { teamId: "tun", aliases: ["Tunisia", "TUN"] },
  { teamId: "can", aliases: ["Canada", "CAN"] },
  { teamId: "cuw", aliases: ["Curaçao", "Curacao", "CUW"] },
  { teamId: "hai", aliases: ["Haiti", "HAI"] },
  { teamId: "mex", aliases: ["Mexico", "MEX"] },
  { teamId: "pan", aliases: ["Panama", "PAN"] },
  { teamId: "usa", aliases: ["United States", "USA", "United States of America"] },
  { teamId: "arg", aliases: ["Argentina", "ARG"] },
  { teamId: "bra", aliases: ["Brazil", "BRA"] },
  { teamId: "col", aliases: ["Colombia", "COL"] },
  { teamId: "ecu", aliases: ["Ecuador", "ECU"] },
  { teamId: "par", aliases: ["Paraguay", "PAR"] },
  { teamId: "uru", aliases: ["Uruguay", "URU"] },
  { teamId: "nzl", aliases: ["New Zealand", "NZL"] },
  { teamId: "aut", aliases: ["Austria", "AUT"] },
  { teamId: "bel", aliases: ["Belgium", "BEL"] },
  { teamId: "bih", aliases: ["Bosnia and Herzegovina", "Bosnia-Herzegovina", "BIH"] },
  { teamId: "cro", aliases: ["Croatia", "CRO"] },
  { teamId: "cze", aliases: ["Czech Republic", "Czechia", "CZE"] },
  { teamId: "eng", aliases: ["England", "ENG"] },
  { teamId: "fra", aliases: ["France", "FRA"] },
  { teamId: "ger", aliases: ["Germany", "GER"] },
  { teamId: "ned", aliases: ["Netherlands", "NED", "Holland"] },
  { teamId: "nor", aliases: ["Norway", "NOR"] },
  { teamId: "por", aliases: ["Portugal", "POR"] },
  { teamId: "sco", aliases: ["Scotland", "SCO"] },
  { teamId: "esp", aliases: ["Spain", "ESP"] },
  { teamId: "swe", aliases: ["Sweden", "SWE"] },
  { teamId: "sui", aliases: ["Switzerland", "SUI"] },
  { teamId: "tur", aliases: ["Turkey", "Türkiye", "Turkiye", "TUR"] },
];
