import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { mockTeams } from "../../src/data/mockTeams.ts";
import type { TeamId, TeamRatingV2 } from "../../src/lib/simulator/types.ts";
import type { ValidationWarning } from "./schemas.ts";

const GENERATED_FILE_WARNING = "Do not edit manually.";

export interface GeneratedRatingsJson {
  generatedFileWarning: typeof GENERATED_FILE_WARNING;
  ratingsByTeamId: Record<TeamId, TeamRatingV2>;
}

export interface GeneratedRatingsMetadata {
  generatedFileWarning: typeof GENERATED_FILE_WARNING;
  modelVersion: "v2";
  sourceFile: string;
  sourceDateRange: {
    from: string;
    to: string;
  };
  teamCount: number;
  fixture: true;
  warnings: ValidationWarning[];
  generationTimestampPolicy: string;
}

export interface GeneratedRatingsArtifacts {
  ratingsJson: string;
  metadataJson: string;
  typescript: string;
}

export interface WriteGeneratedRatingsOptions {
  ratingsByTeamId: Record<TeamId, TeamRatingV2>;
  metadata: GeneratedRatingsMetadata;
  ratingsJsonPath: string;
  metadataJsonPath: string;
  typescriptPath: string;
}

export async function writeGeneratedRatingsArtifacts(
  options: WriteGeneratedRatingsOptions,
): Promise<void> {
  const artifacts = createGeneratedRatingsArtifacts(
    options.ratingsByTeamId,
    options.metadata,
  );

  await Promise.all([
    writeTextFile(options.ratingsJsonPath, artifacts.ratingsJson),
    writeTextFile(options.metadataJsonPath, artifacts.metadataJson),
    writeTextFile(options.typescriptPath, artifacts.typescript),
  ]);
}

export function createGeneratedRatingsArtifacts(
  ratingsByTeamId: Record<TeamId, TeamRatingV2>,
  metadata: GeneratedRatingsMetadata,
): GeneratedRatingsArtifacts {
  return {
    ratingsJson: `${JSON.stringify(createGeneratedRatingsJson(ratingsByTeamId), null, 2)}\n`,
    metadataJson: `${JSON.stringify(metadata, null, 2)}\n`,
    typescript: createGeneratedRatingsTypeScript(ratingsByTeamId),
  };
}

export function createGeneratedRatingsMetadata(options: {
  sourceFile: string;
  sourceDates: string[];
  teamCount: number;
  warnings: ValidationWarning[];
}): GeneratedRatingsMetadata {
  const sortedSourceDates = [...new Set(options.sourceDates)].sort();

  return {
    generatedFileWarning: GENERATED_FILE_WARNING,
    modelVersion: "v2",
    sourceFile: options.sourceFile,
    sourceDateRange: {
      from: sortedSourceDates[0] ?? "",
      to: sortedSourceDates[sortedSourceDates.length - 1] ?? "",
    },
    teamCount: options.teamCount,
    fixture: true,
    warnings: options.warnings,
    generationTimestampPolicy:
      "No wall-clock timestamp is written; generated artifacts are deterministic for identical inputs.",
  };
}

function createGeneratedRatingsJson(
  ratingsByTeamId: Record<TeamId, TeamRatingV2>,
): GeneratedRatingsJson {
  return {
    generatedFileWarning: GENERATED_FILE_WARNING,
    ratingsByTeamId: orderRatingsByMockTeams(ratingsByTeamId),
  };
}

function createGeneratedRatingsTypeScript(
  ratingsByTeamId: Record<TeamId, TeamRatingV2>,
): string {
  const ratingsJson = JSON.stringify(orderRatingsByMockTeams(ratingsByTeamId), null, 2);

  return `import type { TeamId, TeamRatingV2 } from "@/src/lib/simulator/types";

// Generated by npm run ratings:generate.
// Do not edit manually.
// Synthetic fixture data only; not real Elo data.
// Elo-derived attack/defense/recentForm/squadStrength values are compatibility proxies, not independent measurements.
export const teamRatingsV2GeneratedByTeamId: Record<TeamId, TeamRatingV2> = ${ratingsJson};
`;
}

function orderRatingsByMockTeams(
  ratingsByTeamId: Record<TeamId, TeamRatingV2>,
): Record<TeamId, TeamRatingV2> {
  return Object.fromEntries(
    mockTeams.map((team) => {
      const rating = ratingsByTeamId[team.id];

      if (!rating) {
        throw new Error(`Cannot write generated ratings: missing rating for "${team.id}".`);
      }

      return [team.id, rating];
    }),
  );
}

async function writeTextFile(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, "utf8");
}
