import type { ThirdPlaceAssignment } from "../types";

export type ThirdPlaceAssignmentLookupEntry = ThirdPlaceAssignment;

export const THIRD_PLACE_ASSIGNMENT_METADATA = {
  version: "fifa-world-cup-26-regulations-annex-c-may-2026",
  sourceTitle: "Regulations for the FIFA World Cup 26",
  sourceUrl: "https://digitalhub.fifa.com/m/636f5c9c6f29771f/original/FWC2026_regulations_EN.pdf",
  sourceDocumentDate: "May 2026",
  annex: "Annex C",
  combinationCount: 495,
} as const;

// Static transcription of FIFA World Cup 26 Regulations Annex C.
// Each key is the canonical sorted set of eight third-place groups that qualify.
export const THIRD_PLACE_ASSIGNMENT_LOOKUP: Readonly<Record<string, ThirdPlaceAssignmentLookupEntry>> = {
  EFGHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "F",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DFGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DEGHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DEFHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DEFGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DEFGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DEFGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  DEFGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  DEFGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CFGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CEGHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CEFHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CEFGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CEFGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CEFGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CEFGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  CEFGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CDGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDFHIJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDFGIJKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDFGHJKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDFGHIKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDFGHIJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  CDFGHIJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CDEHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  CDEGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CDEFIJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEFHJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEFHIKL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEFHIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  CDEFHIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CDEFGJKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEFGIKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEFGIJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  CDEFGIJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CDEFGHKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  CDEFGHJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  CDEFGHJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  CDEFGHIL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  CDEFGHIK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  CDEFGHIJ: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  BFGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BEGHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "B",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BEFHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BEFGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BEFGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BEFGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BEFGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BEFGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BDGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDFHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDFGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDFGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDFGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDFGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BDFGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BDEHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BDEGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BDEFIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEFHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEFHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEFHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BDEFHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BDEFGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEFGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEFGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BDEFGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BDEFGHKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BDEFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  BDEFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  BDEFGHIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BDEFGHIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BDEFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  BCGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCFHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCFGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCFGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCFGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCFGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCFGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCEHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCEGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCEFIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEFHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEFHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEFHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCEFHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCEFGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEFGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEFGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCEFGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCEFGHKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCEFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  BCEFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  BCEFGHIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCEFGHIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCEFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  BCDHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDFIJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDFHJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDFHIKL: {
    third_vs_1A: "C",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDFHIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDFHIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDFGJKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDFGIKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDFGIJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDFGIJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDFGHKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDFGHJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  BCDFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  BCDFGHIL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDFGHIK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  BCDEIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDEHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDEGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "I",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDEGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDEGHKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  BCDEGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  BCDEGHIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDEGHIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "H",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDEGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  BCDEFJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "E",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEFIKL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEFIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "E",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDEFIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "E",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDEFHKL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEFHJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  BCDEFHJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  BCDEFHIL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDEFHIK: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDEFHIJ: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  BCDEFGKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "E",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  BCDEFGJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  BCDEFGJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  BCDEFGIL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "E",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  BCDEFGIK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "E",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  BCDEFGIJ: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  BCDEFGHL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  BCDEFGHK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  BCDEFGHJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "J",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "E",
  },
  BCDEFGHI: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "H",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  AFGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  AEGHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "A",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  AEFHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  AEFGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  AEFGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  AEFGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  AEFGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  AEFGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ADGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADFHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADFGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADFGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADFGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADFGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ADFGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ADEHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ADEGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ADEFIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEFHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEFHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEFHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ADEFHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ADEFGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEFGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEFGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ADEFGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ADEFGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ADEFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ADEFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ADEFGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ADEFGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ADEFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ACGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACFHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACFGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACFGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACFGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACFGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACFGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACEHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACEGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACEFIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEFHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEFHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEFHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACEFHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACEFGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEFGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEFGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACEFGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACEFGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACEFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ACEFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ACEFGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACEFGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACEFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ACDHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDFIJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDFHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDFHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "F",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDFHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDFHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDFGJKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDFGIKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDFGIJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDFGIJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDFGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDFGHJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "H",
  },
  ACDFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  ACDFGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDFGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  ACDEIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDEHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDEGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "I",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDEGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDEGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ACDEGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ACDEGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDEGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDEGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ACDEFJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEFIKL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "I",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEFIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDEFIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDEFHKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEFHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ACDEFHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  ACDEFHIL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDEFHIK: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDEFHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  ACDEFGKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ACDEFGJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ACDEFGJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ACDEFGIL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ACDEFGIK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ACDEFGIJ: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ACDEFGHL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "F",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ACDEFGHK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  ACDEFGHJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "J",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "E",
  },
  ACDEFGHI: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "E",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  ABGHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABFHIJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABFGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABFGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABFGHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABFGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABFGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABEHIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEGIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEGHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEGHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEGHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABEGHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "H",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABEFIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEFHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEFHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEFHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABEFHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABEFGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEFGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEFGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABEFGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABEFGHKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABEFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABEFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABEFGHIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABEFGHIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABEFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABDHIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDGHIKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDFIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDFHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDFHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDFHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDFHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDFGJKL: {
    third_vs_1A: "F",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDFGIKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDFGIJL: {
    third_vs_1A: "F",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDFGIJK: {
    third_vs_1A: "F",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDFGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABDFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABDFGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDFGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABDEIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDEHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDEGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDEGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDEGHKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABDEGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABDEGHIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDEGHIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDEGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABDEFJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEFIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEFIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDEFIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDEFHKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEFHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABDEFHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABDEFHIL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDEFHIK: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDEFHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABDEFGKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABDEFGJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABDEFGJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABDEFGIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABDEFGIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABDEFGIJ: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABDEFGHL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABDEFGHK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABDEFGHJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "J",
  },
  ABDEFGHI: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCHIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCGIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCGHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCGHIKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCGHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCGHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCFIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCFHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCFHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCFHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCFHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCFGJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCFGIKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCFGIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCFGIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "F",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCFGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCFGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABCFGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABCFGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCFGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCFGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABCEIJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "C",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEHJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEHIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEHIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCEHIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCEGJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEGIKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "A",
    third_vs_1G: "I",
    third_vs_1I: "C",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEGIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCEGIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCEGHKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCEGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCEGHIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCEGHIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "H",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCEGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCEFJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEFIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEFIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCEFIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCEFHKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEFHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCEFHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCEFHIL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCEFHIK: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCEFHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCEFGKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCEFGJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABCEFGJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABCEFGIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCEFGIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCEFGIJ: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABCEFGHL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCEFGHK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCEFGHJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "J",
  },
  ABCEFGHI: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCDIJKL: {
    third_vs_1A: "I",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDHJKL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDHIKL: {
    third_vs_1A: "H",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDHIJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDHIJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDGJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDGIKL: {
    third_vs_1A: "I",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDGIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDGIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "G",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDGHKL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDGHJL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABCDGHJK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABCDGHIL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDGHIK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDGHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABCDFJKL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDFIKL: {
    third_vs_1A: "C",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDFIJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDFIJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDFHKL: {
    third_vs_1A: "H",
    third_vs_1B: "F",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDFHJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "H",
  },
  ABCDFHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  ABCDFHIL: {
    third_vs_1A: "H",
    third_vs_1B: "F",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDFHIK: {
    third_vs_1A: "H",
    third_vs_1B: "F",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDFHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  ABCDFGKL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDFGJL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABCDFGJK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABCDFGIL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDFGIK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDFGIJ: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABCDFGHL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "H",
  },
  ABCDFGHK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  ABCDFGHJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "J",
  },
  ABCDFGHI: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  ABCDEJKL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDEIKL: {
    third_vs_1A: "E",
    third_vs_1B: "I",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDEIJL: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDEIJK: {
    third_vs_1A: "E",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDEHKL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDEHJL: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCDEHJK: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCDEHIL: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDEHIK: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDEHIJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCDEGKL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDEGJL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "J",
  },
  ABCDEGJK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "J",
    third_vs_1L: "K",
  },
  ABCDEGIL: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDEGIK: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDEGIJ: {
    third_vs_1A: "E",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "I",
    third_vs_1L: "J",
  },
  ABCDEGHL: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCDEGHK: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCDEGHJ: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "J",
  },
  ABCDEGHI: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCDEFKL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "K",
  },
  ABCDEFJL: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCDEFJK: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCDEFIL: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "I",
  },
  ABCDEFIK: {
    third_vs_1A: "C",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "I",
    third_vs_1L: "K",
  },
  ABCDEFIJ: {
    third_vs_1A: "C",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCDEFHL: {
    third_vs_1A: "H",
    third_vs_1B: "F",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "D",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCDEFHK: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "K",
  },
  ABCDEFHJ: {
    third_vs_1A: "H",
    third_vs_1B: "J",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "E",
  },
  ABCDEFHI: {
    third_vs_1A: "H",
    third_vs_1B: "E",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "I",
  },
  ABCDEFGL: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "L",
    third_vs_1L: "E",
  },
  ABCDEFGK: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "K",
  },
  ABCDEFGJ: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "J",
  },
  ABCDEFGI: {
    third_vs_1A: "C",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "D",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "E",
    third_vs_1L: "I",
  },
  ABCDEFGH: {
    third_vs_1A: "H",
    third_vs_1B: "G",
    third_vs_1D: "B",
    third_vs_1E: "C",
    third_vs_1G: "A",
    third_vs_1I: "F",
    third_vs_1K: "D",
    third_vs_1L: "E",
  },
};
